name = "translator-api"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "translator-db"
database_id = "f60659e6-2e68-4757-b174-ccc0fd06d29f"

[[kv_namespaces]]
binding = "CACHE"
id = "6b1ef66b411048a28253b81ae1ad664b"

[vars]
DEEPL_KEY = ""  # set via wrangler secret put
MYMEMORY_ENABLED = "true"
DEEPL_ENABLED = "true"
BETA_MAX_USES = "10"
JOKE_MODE = "false"  # set to "true" on April 1 for fun
